#=========================================================
# Copyright (c) 2021 baiyunxue
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/baiyunxue/Compile-Lede-Openwrt
# Description: Build OpenWrt using GitHub Actions
#=========================================================

name: by-Openwrt

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: æ£€æŸ¥ã€‚ã€‚ã€‚ã€‚ã€‚ã€‚åˆå§‹ç¯å¢ƒ
        uses: actions/checkout@master

      - name: æ­£åœ¨è½½å…¥Ubuntuã€‚ã€‚ã€‚ã€‚ã€‚
        run: |
          sudo apt-get update
          sudo apt-get -y install build-essential ccache ecj fastjar file g++ gawk \
            gettext git java-propose-classpath libelf-dev libncurses5-dev \
            libncursesw5-dev libssl-dev python python2.7-dev python3 unzip wget \
            python3-distutils python3-setuptools python3-dev rsync subversion swig time \
            xsltproc zlib1g-dev 

      - name: å…‹éš†æºä»£ç 
        run: |
          git clone -b openwrt-19.07 https://github.com/openwrt/openwrt
          cd openwrt
          sed -i '$a src-git ZDY https://github.com/baiyunxue/ZDY.git' feeds.conf.default
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      
      - name: SSHè¿æ¥è‡³Actionsäº‘æœåŠ¡å™¨
        uses: P3TERX/ssh2actions@v1.0.0
        if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
        env:
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
   
      - name: ä¸‹è½½ç¼–è¯‘æ‰€éœ€è¦çš„dlåŒ…
        run: |
          cd openwrt
          make -j8 download V=s   
          
      - name: å¼€å§‹ç¼–è¯‘å›ºä»¶ï¼šè¯·ç¨ç­‰..........(å¤§æ¦‚2å°æ—¶å·¦å³)
        run: |
          cd openwrt
          make -j1 V=s
          
      - name: æ£€æŸ¥ç©ºé—´ä½¿ç”¨æƒ…å†µ
      if: (!cancelled())
      run: df -hT

    - name: ä¸Šä¼ åˆ°æ–‡ä»¶å¤¹
      uses: actions/upload-artifact@main
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
      with:
        name: OpenWrt_bin${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: openwrt/bin

    - name: æ•´ç†binæ–‡ä»¶
      id: organize
      if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
      run: |
        cd openwrt/bin/targets/*/*
        rm -rf packages
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "::set-output name=status::success"
    - name: ä¸Šè½½å›ºä»¶åˆ°ç›®å½•
      uses: actions/upload-artifact@main
      if: steps.organize.outputs.status == 'success' && !cancelled()
      with:
        name: OpenWrt_firmware${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: ${{ env.FIRMWARE }}

    - name: ä¸Šä¼ å›ºä»¶åˆ°-ã€Šå¥¶ç‰›å¿«ä¼ ã€‹
      id: cowtransfer
      if: steps.organize.outputs.status == 'success' && env.UPLOAD_COWTRANSFER == 'true' && !cancelled()
      run: |
        curl -fsSL git.io/file-transfer | sh
        ./transfer cow --block 2621440 -s -p 64 --no-progress ${FIRMWARE} 2>&1 | tee cowtransfer.log
        echo "::warning file=cowtransfer.com::$(cat cowtransfer.log | grep https)"
        echo "::set-output name=url::$(cat cowtransfer.log | grep https | cut -f3 -d" ")"
    - name: ä¸Šä¼ å›ºä»¶åˆ°-ã€Šwetransfeã€‹
      id: wetransfer
      if: steps.organize.outputs.status == 'success' && env.UPLOAD_WETRANSFER == 'true' && !cancelled()
      run: |
        curl -fsSL git.io/file-transfer | sh
        ./transfer wet -s -p 16 --no-progress ${FIRMWARE} 2>&1 | tee wetransfer.log
        echo "::warning file=wetransfer.com::$(cat wetransfer.log | grep https)"
        echo "::set-output name=url::$(cat wetransfer.log | grep https | cut -f3 -d" ")"
    - name: ç”Ÿæˆé‡Šæ”¾æ ‡è®°
      id: tag
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      run: |
        echo "::set-output name=release_tag::$(date +"%Y.%m.%d-%H%M")"
        touch release.txt
        [ $UPLOAD_COWTRANSFER = true ] && echo "ğŸ”— [Cowtransfer](${{ steps.cowtransfer.outputs.url }})" >> release.txt
        [ $UPLOAD_WETRANSFER = true ] && echo "ğŸ”— [WeTransfer](${{ steps.wetransfer.outputs.url }})" >> release.txt
        echo "::set-output name=status::success"
    - name: ä¸Šä¼ å›ºä»¶å‘å¸ƒ
      uses: softprops/action-gh-release@v1
      if: steps.tag.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        body_path: release.txt
        files: ${{ env.FIRMWARE }}/*

    - name: åˆ é™¤å·¥ä½œè¿è¡Œæµç¨‹
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 3

    - name: ç§»é™¤æ—§çš„å·¥ä½œæ–‡ä»¶é‡Šæ”¾ç©ºé—´
      uses: dev-drprasad/delete-older-releases@v0.1.0
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      with:
        keep_latest: 3
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
